POST http://localhost:3030/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE2MjUxOTA4ODEsImV4cCI6MTYyNTI3NzI4MSwiYXVkIjoiaHR0cDovL2Vjb21tZXJjZS5jb20iLCJpc3MiOiJmZWF0aGVycyIsInN1YiI6IjYwZGU0NWJkMDc3ODE5MWRlOGRiNDYyYiIsImp0aSI6IjhjMGFmZmU0LWE0YjgtNGM3NS05YzJkLTlmNGI2ZGMyMGU4ZSJ9.us7byCFEPx2uZP_T1aq52UAE6i2h5g7ml3kzAkXYIBc

{
    "name": "Computadoras"
}

### List categories
GET http://localhost:3030/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE2MjUxOTA4ODEsImV4cCI6MTYyNTI3NzI4MSwiYXVkIjoiaHR0cDovL2Vjb21tZXJjZS5jb20iLCJpc3MiOiJmZWF0aGVycyIsInN1YiI6IjYwZGU0NWJkMDc3ODE5MWRlOGRiNDYyYiIsImp0aSI6IjhjMGFmZmU0LWE0YjgtNGM3NS05YzJkLTlmNGI2ZGMyMGU4ZSJ9.us7byCFEPx2uZP_T1aq52UAE6i2h5g7ml3kzAkXYIBc
