POST http://localhost:3030/api/categories
Content-Type: application/json
Authorization: Bearer <token>

{
    "name": ""
}

### List categories
GET http://localhost:3030/api/categories
Authorization: Bearer <token>
