### Create a new product
POST http://localhost:3030/api/products
Content-Type: application/json
Authorization: Bearer <token>

{
    "title": "",
    "description": "",
    "image": "",
    "price": 0
}

### Get lis products
GET http://localhost:3030/api/products
Authorization: Bearer <token>
