### Create a new user
POST http://localhost:3030/api/users
Content-Type: application/json

{
    "first_name": "Nelson Ivan",
    "last_name": "Zaldivar Morales",
    "email": "ivanzaldivar16@gmail.com",
    "password": "Holahola123@"
}

### Get list users
GET http://localhost:3030/api/users
